[package]
name = "capricorn"
version = "0.1.0"
authors = ["Phillip Davies <philliptdavies@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-rt = "0.15.1"
